"""new generation

Revision ID: 44b8d2969643
Revises: 70beb2fa9f9d
Create Date: 2025-05-15 22:20:14.771577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b8d2969643'
down_revision: Union[str, None] = '70beb2fa9f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'updated_at')
    op.drop_column('institutions', 'created_at')
    op.drop_column('institutions', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users_institutions', 'updated_at')
    op.drop_column('users_institutions', 'created_at')
    op.drop_column('users_institutions', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_institutions', sa.Column('deleted_at', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users_institutions', sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users_institutions', sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('institutions', sa.Column('deleted_at', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('institutions', sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('institutions', sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
