"""new generation

Revision ID: f3b70ecd92ff
Revises: 44b8d2969643
Create Date: 2025-05-15 22:21:51.740856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b70ecd92ff'
down_revision: Union[str, None] = '44b8d2969643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('institutions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('institutions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users_institutions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users_institutions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users_institutions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_institutions', 'deleted_at')
    op.drop_column('users_institutions', 'updated_at')
    op.drop_column('users_institutions', 'created_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('institutions', 'deleted_at')
    op.drop_column('institutions', 'updated_at')
    op.drop_column('institutions', 'created_at')
    # ### end Alembic commands ###
